name: Python 测试

on:
  workflow_dispatch:

jobs:
  checkin-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      # 测试中，请勿使用
      with:
        ref: dev
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install
      run: pip install lxml requests
    - name: Execute
      env:
        TZ: Asia/Shanghai
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_PASS: ${{ secrets.SECRET_PASS }}
        SECRET_BOUND: ${{ secrets.SECRET_BOUND }}
        SECRET_DATA: ${{ secrets.SECRET_DATA }}
        SECRET_SCKEY: ${{ secrets.SECRET_SCKEY }}
      run: python Actions/checkin.py | tee -a Logs/checkin-python.log
    - name: Commit
      env:
        TZ: Asia/Shanghai
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Logs/checkin-python.log
        git commit -m \
          "Update python log at \
          $(date +"%Y-%m-%d %H:%M") \
          "
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # 测试中，请勿使用
        branch: dev
